services:
  - type: web
    name: taskflow-app
    env: python
    plan: free
    buildCommand: |
      # Install Node.js for frontend build
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      
      # Build React frontend
      cd frontend
      npm install
      npm run build
      cd ..
      
      # Install Python dependencies
      cd backend
      pip install -r requirements.txt
      
      # Run database migrations
      python manage.py migrate --noinput
      
      # Collect static files
      python manage.py collectstatic --noinput
      cd ..
    startCommand: |
      cd backend
      python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: taskflow-copy.onrender.com
      - key: SECRET_KEY
        generateValue: true
