# Generated by Django 5.2.6 on 2025-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_task_completed_at_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
    ]
