# Generated by Django 5.2.6 on 2025-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_project_attachment_project_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequence',
            field=models.IntegerField(blank=True, help_text='Per-project sequence starting at 1', null=True),
        ),
    ]
