# Generated by Django 5.2.6 on 2025-09-17 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_projectchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='ACCEPTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('TASK_UPDATE', 'Task Update'), ('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_INVITATION_ACCEPTED', 'Project Invitation Accepted'), ('PROJECT_INVITATION_DECLINED', 'Project Invitation Declined')], max_length=32),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Project Owner'), ('SCRUM_MASTER', 'Scrum Master'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
