# Generated by Django 5.2.6 on 2025-09-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_projectchatmessage_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
