# Generated by Django 5.2.6 on 2025-09-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_projectchatmessage_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('TASK_UPDATE', 'Task Update'), ('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_INVITATION_ACCEPTED', 'Project Invitation Accepted'), ('PROJECT_INVITATION_DECLINED', 'Project Invitation Declined'), ('PROJECT_INVITE', 'Project Invite'), ('PROJECT_INVITE_RESPONSE', 'Project Invite Response'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('COMMENT_MENTION', 'Comment Mention')], max_length=32),
        ),
    ]
