# Generated by Django 5.2.6 on 2025-09-20 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='reporter_name',
        ),
        migrations.AddField(
            model_name='project',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('TASK_UPDATE', 'Task Update'), ('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_INVITATION_ACCEPTED', 'Project Invitation Accepted'), ('PROJECT_INVITATION_DECLINED', 'Project Invitation Declined'), ('PROJECT_INVITE', 'Project Invite'), ('PROJECT_INVITE_RESPONSE', 'Project Invite Response'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('COMMENT_MENTION', 'Comment Mention'), ('PROJECT_REPORTER_ASSIGNED', 'Project Reporter Assigned')], max_length=32),
        ),
    ]
