# Generated by Django 5.2.6 on 2025-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_remove_project_reporter_name_project_reporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, help_text='Formatted notification message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('TASK_UPDATE', 'Task Update'), ('PROJECT_INVITATION', 'Project Invitation'), ('PROJECT_INVITATION_ACCEPTED', 'Project Invitation Accepted'), ('PROJECT_INVITATION_DECLINED', 'Project Invitation Declined'), ('PROJECT_INVITE', 'Project Invite'), ('PROJECT_INVITE_RESPONSE', 'Project Invite Response'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('COMMENT_MENTION', 'Comment Mention'), ('PROJECT_REPORTER_ASSIGNED', 'Project Reporter Assigned'), ('PROJECT_DEADLINE_CHANGED', 'Project Deadline Changed'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_REMOVED', 'Project Removed'), ('TASK_DEADLINE_REMINDER', 'Task Deadline Reminder'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_REMOVED', 'Task Removed'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded'), ('REMINDER_24H', '24 Hour Reminder'), ('REMINDER_IDLE', 'Idle Task Reminder'), ('DAILY_SUMMARY', 'Daily Summary'), ('WEEKLY_UPDATE', 'Weekly Update'), ('PASSWORD_CHANGED', 'Password Changed'), ('APP_UPDATE', 'App Update'), ('NOTIFICATIONS_SNOOZED', 'Notifications Snoozed')], max_length=32),
        ),
    ]
