# Generated by Django 5.2.6 on 2025-09-21 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_created', models.BooleanField(default=True, help_text='Notify when projects/tasks are created')),
                ('notifications_assigned', models.BooleanField(default=True, help_text='Notify when tasks/projects are assigned to user')),
                ('notifications_reported', models.BooleanField(default=True, help_text='Notify when user is set as reporter')),
                ('notifications_watching', models.BooleanField(default=True, help_text='Notify when user is watching a project/task')),
                ('notifications_mentions', models.BooleanField(default=True, help_text='Notify when someone mentions the user (@mailID)')),
                ('notifications_approval', models.BooleanField(default=True, help_text='Notify when someone adds the user as an approver')),
                ('do_not_disturb_enabled', models.BooleanField(default=False, help_text='Whether Do Not Disturb is currently active')),
                ('do_not_disturb_until', models.DateTimeField(blank=True, help_text='Do Not Disturb expires at this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
