# Generated by Django 5.2.6 on 2025-09-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notifications_approval',
        ),
    ]
